/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type TodoDto,
    TodoDtoFromJSON,
    TodoDtoToJSON,
} from '../models/TodoDto';
import {
    type TodoForAdd,
    TodoForAddFromJSON,
    TodoForAddToJSON,
} from '../models/TodoForAdd';

export interface ApiTodoDeleteRequest {
    guid?: string;
}

export interface ApiTodoIdGetRequest {
    id: string;
}

export interface ApiTodoPatchRequest {
    guid?: string;
    status?: string;
}

export interface ApiTodoPostRequest {
    todoForAdd?: TodoForAdd;
}

/**
 * 
 */
export class TodoApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiTodoDelete without sending the request
     */
    async apiTodoDeleteRequestOpts(requestParameters: ApiTodoDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['guid'] != null) {
            queryParameters['guid'] = requestParameters['guid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiTodoDeleteRaw(requestParameters: ApiTodoDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<boolean>> {
        const requestOptions = await this.apiTodoDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<boolean>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTodoDelete(requestParameters: ApiTodoDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
        const response = await this.apiTodoDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTodoGet without sending the request
     */
    async apiTodoGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiTodoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoDto>>> {
        const requestOptions = await this.apiTodoGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoDtoFromJSON));
    }

    /**
     */
    async apiTodoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoDto>> {
        const response = await this.apiTodoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTodoIdGet without sending the request
     */
    async apiTodoIdGetRequestOpts(requestParameters: ApiTodoIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Todo/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiTodoIdGetRaw(requestParameters: ApiTodoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDto>> {
        const requestOptions = await this.apiTodoIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoIdGet(requestParameters: ApiTodoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDto> {
        const response = await this.apiTodoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTodoPatch without sending the request
     */
    async apiTodoPatchRequestOpts(requestParameters: ApiTodoPatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['guid'] != null) {
            queryParameters['guid'] = requestParameters['guid'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiTodoPatchRaw(requestParameters: ApiTodoPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTodoPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTodoPatch(requestParameters: ApiTodoPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTodoPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTodoPost without sending the request
     */
    async apiTodoPostRequestOpts(requestParameters: ApiTodoPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoForAddToJSON(requestParameters['todoForAdd']),
        };
    }

    /**
     */
    async apiTodoPostRaw(requestParameters: ApiTodoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTodoPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTodoPost(requestParameters: ApiTodoPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTodoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
