name: dev
variables:
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg2NjlhZDgxLTk2ODItNDNmZi1hOTEwLTQ1MTZjMTRmNGVkZCIsIm5iZiI6MTc4OTA0MTM2MSwiZXhwIjoxNzg5MDQ0OTYxLCJpc3MiOiJXZWJBcHBJc3N1ZXIiLCJhdWQiOiJXZWJBcHBBdWRpZW5jZSJ9.QHGyZL_RQY-hQETVGz9FE5cR9I2kmf7q8OEB0KpV3U4
    description: ""
