name: dev
variables:
  - name: token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg2NjlhZDgxLTk2ODItNDNmZi1hOTEwLTQ1MTZjMTRmNGVkZCIsIm5iZiI6MTc4OTQ4MTgwMywiZXhwIjoxNzg5NDg1NDAzLCJpc3MiOiJXZWJBcHBJc3N1ZXIiLCJhdWQiOiJXZWJBcHBBdWRpZW5jZSJ9.V5s20TRj10SHOaGTG2UTBnSUsNvH_xj-aySJRtjn_RM
  - name: baseUrl
    value: 192.168.0.100:5110
