// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLife.Data.Repository;

#nullable disable

namespace MyLife.Data.Migrations
{
    [DbContext(typeof(AppStorage))]
    [Migration("20260609060739_OptimizeTags")]
    partial class OptimizeTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyLife.Data.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Avatar")
                        .HasColumnType("char(36)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("UID");

                    b.HasIndex("Name");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyLife.Data.Entities.CorpusEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CorpusContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UID");

                    b.ToTable("Corpus");
                });

            modelBuilder.Entity("MyLife.Data.Entities.DemoEntity", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Serial"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Serial");

                    b.ToTable("Demo");
                });

            modelBuilder.Entity("MyLife.Data.Entities.FileMetaEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DesensitizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UID");

                    b.ToTable("FileMeta");
                });

            modelBuilder.Entity("MyLife.Data.Entities.FileTagEntity", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("MyLife.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid?>("SubscriptionIcon")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubscriptionLink")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubscriptionPlatform")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UID")
                        .HasColumnType("char(36)");

                    b.HasKey("SID");

                    b.HasIndex("UID");

                    b.HasIndex("SubscriptionPlatform", "SubscriptionLink");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MyLife.Data.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCategory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("UID");

                    b.HasIndex("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MyLife.Data.Entities.TodoEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FTID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.HasIndex("FTID");

                    b.ToTable("TodoList");
                });

            modelBuilder.Entity("MyLife.Data.Entities.FileTagEntity", b =>
                {
                    b.HasOne("MyLife.Data.Entities.FileMetaEntity", "File")
                        .WithMany("FileTags")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyLife.Data.Entities.TagEntity", "Tag")
                        .WithMany("FileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyLife.Data.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("MyLife.Data.Entities.AccountEntity", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyLife.Data.Entities.TodoEntity", b =>
                {
                    b.HasOne("MyLife.Data.Entities.TodoEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("FTID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyLife.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MyLife.Data.Entities.FileMetaEntity", b =>
                {
                    b.Navigation("FileTags");
                });

            modelBuilder.Entity("MyLife.Data.Entities.TagEntity", b =>
                {
                    b.Navigation("FileTags");
                });
#pragma warning restore 612, 618
        }
    }
}
