/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountProfile
 */
export interface AccountProfile {
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    desc?: string | null;
}

/**
 * Check if a given object implements the AccountProfile interface.
 */
export function instanceOfAccountProfile(value: object): value is AccountProfile {
    return true;
}

export function AccountProfileFromJSON(json: any): AccountProfile {
    return AccountProfileFromJSONTyped(json, false);
}

export function AccountProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'desc': json['desc'] == null ? undefined : json['desc'],
    };
}

export function AccountProfileToJSON(json: any): AccountProfile {
    return AccountProfileToJSONTyped(json, false);
}

export function AccountProfileToJSONTyped(value?: AccountProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'desc': value['desc'],
    };
}

