/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionDto } from './SubscriptionDto';
import {
    SubscriptionDtoFromJSON,
    SubscriptionDtoFromJSONTyped,
    SubscriptionDtoToJSON,
    SubscriptionDtoToJSONTyped,
} from './SubscriptionDto';

/**
 * 
 * @export
 * @interface AccountDto
 */
export interface AccountDto {
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    desc?: string | null;
    /**
     * 
     */
    avatar?: string | null;
    /**
     * 
     */
    subscriptions?: Array<SubscriptionDto> | null;
}

/**
 * Check if a given object implements the AccountDto interface.
 */
export function instanceOfAccountDto(value: object): value is AccountDto {
    return true;
}

export function AccountDtoFromJSON(json: any): AccountDto {
    return AccountDtoFromJSONTyped(json, false);
}

export function AccountDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'desc': json['desc'] === undefined ? undefined : json['desc'] === null ? null : json['desc'],
        'avatar': json['avatar'] === undefined ? undefined : json['avatar'] === null ? null : json['avatar'],
        'subscriptions': json['subscriptions'] === undefined ? undefined : json['subscriptions'] === null ? null : ((json['subscriptions'] as Array<any>).map(SubscriptionDtoFromJSON)),
    };
}

export function AccountDtoToJSON(json: any): AccountDto {
    return AccountDtoToJSONTyped(json, false);
}

export function AccountDtoToJSONTyped(value?: AccountDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'desc': value['desc'],
        'avatar': value['avatar'],
        'subscriptions': value['subscriptions'] == null ? undefined : ((value['subscriptions'] as Array<any>).map(SubscriptionDtoToJSON)),
    };
}

