/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlogCategoryStatistics
 */
export interface BlogCategoryStatistics {
    /**
     * 
     * @type {string}
     * @memberof BlogCategoryStatistics
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BlogCategoryStatistics
     */
    categoryName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BlogCategoryStatistics
     */
    categoryCount?: number;
}

/**
 * Check if a given object implements the BlogCategoryStatistics interface.
 */
export function instanceOfBlogCategoryStatistics(value: object): value is BlogCategoryStatistics {
    return true;
}

export function BlogCategoryStatisticsFromJSON(json: any): BlogCategoryStatistics {
    return BlogCategoryStatisticsFromJSONTyped(json, false);
}

export function BlogCategoryStatisticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogCategoryStatistics {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryCount': json['categoryCount'] == null ? undefined : json['categoryCount'],
    };
}

export function BlogCategoryStatisticsToJSON(json: any): BlogCategoryStatistics {
    return BlogCategoryStatisticsToJSONTyped(json, false);
}

export function BlogCategoryStatisticsToJSONTyped(value?: BlogCategoryStatistics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'categoryName': value['categoryName'],
        'categoryCount': value['categoryCount'],
    };
}

