/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelScheduledBlogPostCommand
 */
export interface CancelScheduledBlogPostCommand {
    /**
     * 
     * @type {string}
     * @memberof CancelScheduledBlogPostCommand
     */
    uid?: string;
}

/**
 * Check if a given object implements the CancelScheduledBlogPostCommand interface.
 */
export function instanceOfCancelScheduledBlogPostCommand(value: object): value is CancelScheduledBlogPostCommand {
    return true;
}

export function CancelScheduledBlogPostCommandFromJSON(json: any): CancelScheduledBlogPostCommand {
    return CancelScheduledBlogPostCommandFromJSONTyped(json, false);
}

export function CancelScheduledBlogPostCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelScheduledBlogPostCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function CancelScheduledBlogPostCommandToJSON(json: any): CancelScheduledBlogPostCommand {
    return CancelScheduledBlogPostCommandToJSONTyped(json, false);
}

export function CancelScheduledBlogPostCommandToJSONTyped(value?: CancelScheduledBlogPostCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

