/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelScheduledFileCommand
 */
export interface CancelScheduledFileCommand {
    /**
     * 
     * @type {string}
     * @memberof CancelScheduledFileCommand
     */
    uid?: string;
}

/**
 * Check if a given object implements the CancelScheduledFileCommand interface.
 */
export function instanceOfCancelScheduledFileCommand(value: object): value is CancelScheduledFileCommand {
    return true;
}

export function CancelScheduledFileCommandFromJSON(json: any): CancelScheduledFileCommand {
    return CancelScheduledFileCommandFromJSONTyped(json, false);
}

export function CancelScheduledFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelScheduledFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function CancelScheduledFileCommandToJSON(json: any): CancelScheduledFileCommand {
    return CancelScheduledFileCommandToJSONTyped(json, false);
}

export function CancelScheduledFileCommandToJSONTyped(value?: CancelScheduledFileCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

