/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryQuery
 */
export interface CategoryQuery {
    /**
     * 
     * @type {boolean}
     * @memberof CategoryQuery
     */
    isAll?: boolean;
}

/**
 * Check if a given object implements the CategoryQuery interface.
 */
export function instanceOfCategoryQuery(value: object): value is CategoryQuery {
    return true;
}

export function CategoryQueryFromJSON(json: any): CategoryQuery {
    return CategoryQueryFromJSONTyped(json, false);
}

export function CategoryQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'isAll': json['isAll'] == null ? undefined : json['isAll'],
    };
}

export function CategoryQueryToJSON(json: any): CategoryQuery {
    return CategoryQueryToJSONTyped(json, false);
}

export function CategoryQueryToJSONTyped(value?: CategoryQuery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isAll': value['isAll'],
    };
}

