/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorpusDto } from './CorpusDto';
import {
    CorpusDtoFromJSON,
    CorpusDtoFromJSONTyped,
    CorpusDtoToJSON,
    CorpusDtoToJSONTyped,
} from './CorpusDto';

/**
 * 
 * @export
 * @interface CorpusDtoPageResult
 */
export interface CorpusDtoPageResult {
    /**
     * 
     * @type {Array<CorpusDto>}
     * @memberof CorpusDtoPageResult
     */
    items?: Array<CorpusDto> | null;
    /**
     * 
     * @type {number}
     * @memberof CorpusDtoPageResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CorpusDtoPageResult
     */
    pageSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CorpusDtoPageResult
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the CorpusDtoPageResult interface.
 */
export function instanceOfCorpusDtoPageResult(value: object): value is CorpusDtoPageResult {
    return true;
}

export function CorpusDtoPageResultFromJSON(json: any): CorpusDtoPageResult {
    return CorpusDtoPageResultFromJSONTyped(json, false);
}

export function CorpusDtoPageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusDtoPageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CorpusDtoFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function CorpusDtoPageResultToJSON(json: any): CorpusDtoPageResult {
    return CorpusDtoPageResultToJSONTyped(json, false);
}

export function CorpusDtoPageResultToJSONTyped(value?: CorpusDtoPageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CorpusDtoToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'hasMore': value['hasMore'],
    };
}

