/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorpusDto
 */
export interface CorpusDto {
    /**
     * 
     * @type {string}
     * @memberof CorpusDto
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof CorpusDto
     */
    corpusContent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CorpusDto
     */
    createDate?: string | null;
}

/**
 * Check if a given object implements the CorpusDto interface.
 */
export function instanceOfCorpusDto(value: object): value is CorpusDto {
    return true;
}

export function CorpusDtoFromJSON(json: any): CorpusDto {
    return CorpusDtoFromJSONTyped(json, false);
}

export function CorpusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'corpusContent': json['corpusContent'] == null ? undefined : json['corpusContent'],
        'createDate': json['createDate'] == null ? undefined : json['createDate'],
    };
}

export function CorpusDtoToJSON(json: any): CorpusDto {
    return CorpusDtoToJSONTyped(json, false);
}

export function CorpusDtoToJSONTyped(value?: CorpusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'corpusContent': value['corpusContent'],
        'createDate': value['createDate'],
    };
}

