/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFileCommand
 */
export interface CreateFileCommand {
    /**
     * Whether uploaded files should be stored as templates.
     * @type {boolean}
     * @memberof CreateFileCommand
     */
    isTemplate?: boolean;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof CreateFileCommand
     */
    file?: Array<Blob> | null;
}

/**
 * Check if a given object implements the CreateFileCommand interface.
 */
export function instanceOfCreateFileCommand(value: object): value is CreateFileCommand {
    return true;
}

export function CreateFileCommandFromJSON(json: any): CreateFileCommand {
    return CreateFileCommandFromJSONTyped(json, false);
}

export function CreateFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'isTemplate': json['isTemplate'] == null ? undefined : json['isTemplate'],
        'file': json['file'] == null ? undefined : json['file'],
    };
}

export function CreateFileCommandToJSON(json: any): CreateFileCommand {
    return CreateFileCommandToJSONTyped(json, false);
}

export function CreateFileCommandToJSONTyped(value?: CreateFileCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isTemplate': value['isTemplate'],
        'file': value['file'],
    };
}

