/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountCommand
 */
export interface CreateAccountCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountCommand
     */
    desc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountCommand
     */
    pwd?: string | null;
}

/**
 * Check if a given object implements the CreateAccountCommand interface.
 */
export function instanceOfCreateAccountCommand(value: object): value is CreateAccountCommand {
    return true;
}

export function CreateAccountCommandFromJSON(json: any): CreateAccountCommand {
    return CreateAccountCommandFromJSONTyped(json, false);
}

export function CreateAccountCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'pwd': json['pwd'] == null ? undefined : json['pwd'],
    };
}

export function CreateAccountCommandToJSON(json: any): CreateAccountCommand {
    return CreateAccountCommandToJSONTyped(json, false);
}

export function CreateAccountCommandToJSONTyped(value?: CreateAccountCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'desc': value['desc'],
        'pwd': value['pwd'],
    };
}

