/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCorpusCommand
 */
export interface CreateCorpusCommand {
    /**
     * 
     */
    content?: string | null;
}

/**
 * Check if a given object implements the CreateCorpusCommand interface.
 */
export function instanceOfCreateCorpusCommand(value: object): value is CreateCorpusCommand {
    return true;
}

export function CreateCorpusCommandFromJSON(json: any): CreateCorpusCommand {
    return CreateCorpusCommandFromJSONTyped(json, false);
}

export function CreateCorpusCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCorpusCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] === undefined ? undefined : json['content'] === null ? null : json['content'],
    };
}

export function CreateCorpusCommandToJSON(json: any): CreateCorpusCommand {
    return CreateCorpusCommandToJSONTyped(json, false);
}

export function CreateCorpusCommandToJSONTyped(value?: CreateCorpusCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

