/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTodoCommand
 */
export interface CreateTodoCommand {
    /**
     * 
     */
    desc?: string | null;
    /**
     * 
     */
    priority?: number;
    /**
     * 
     */
    ftid?: string | null;
}

/**
 * Check if a given object implements the CreateTodoCommand interface.
 */
export function instanceOfCreateTodoCommand(value: object): value is CreateTodoCommand {
    return true;
}

export function CreateTodoCommandFromJSON(json: any): CreateTodoCommand {
    return CreateTodoCommandFromJSONTyped(json, false);
}

export function CreateTodoCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTodoCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'desc': json['desc'] === undefined ? undefined : json['desc'] === null ? null : json['desc'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'ftid': json['ftid'] === undefined ? undefined : json['ftid'] === null ? null : json['ftid'],
    };
}

export function CreateTodoCommandToJSON(json: any): CreateTodoCommand {
    return CreateTodoCommandToJSONTyped(json, false);
}

export function CreateTodoCommandToJSONTyped(value?: CreateTodoCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'desc': value['desc'],
        'priority': value['priority'],
        'ftid': value['ftid'],
    };
}

