/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTagCommand
 */
export interface CreateTagCommand {
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    aliasName?: string | null;
    /**
     * 
     */
    isCategory?: boolean;
}

/**
 * Check if a given object implements the CreateTagCommand interface.
 */
export function instanceOfCreateTagCommand(value: object): value is CreateTagCommand {
    return true;
}

export function CreateTagCommandFromJSON(json: any): CreateTagCommand {
    return CreateTagCommandFromJSONTyped(json, false);
}

export function CreateTagCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTagCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'aliasName': json['aliasName'] === undefined ? undefined : json['aliasName'] === null ? null : json['aliasName'],
        'isCategory': json['isCategory'] == null ? undefined : json['isCategory'],
    };
}

export function CreateTagCommandToJSON(json: any): CreateTagCommand {
    return CreateTagCommandToJSONTyped(json, false);
}

export function CreateTagCommandToJSONTyped(value?: CreateTagCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'aliasName': value['aliasName'],
        'isCategory': value['isCategory'],
    };
}

