/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteCorepusCommand
 */
export interface DeleteCorepusCommand {
    /**
     * 
     * @type {string}
     * @memberof DeleteCorepusCommand
     */
    uid?: string;
}

/**
 * Check if a given object implements the DeleteCorepusCommand interface.
 */
export function instanceOfDeleteCorepusCommand(value: object): value is DeleteCorepusCommand {
    return true;
}

export function DeleteCorepusCommandFromJSON(json: any): DeleteCorepusCommand {
    return DeleteCorepusCommandFromJSONTyped(json, false);
}

export function DeleteCorepusCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteCorepusCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function DeleteCorepusCommandToJSON(json: any): DeleteCorepusCommand {
    return DeleteCorepusCommandToJSONTyped(json, false);
}

export function DeleteCorepusCommandToJSONTyped(value?: DeleteCorepusCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

