/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteFileCommand
 */
export interface DeleteFileCommand {
    /**
     * 
     */
    uid?: string;
}

/**
 * Check if a given object implements the DeleteFileCommand interface.
 */
export function instanceOfDeleteFileCommand(value: object): value is DeleteFileCommand {
    return true;
}

export function DeleteFileCommandFromJSON(json: any): DeleteFileCommand {
    return DeleteFileCommandFromJSONTyped(json, false);
}

export function DeleteFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function DeleteFileCommandToJSON(json: any): DeleteFileCommand {
    return DeleteFileCommandToJSONTyped(json, false);
}

export function DeleteFileCommandToJSONTyped(value?: DeleteFileCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

