/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTodoCommand
 */
export interface DeleteTodoCommand {
    /**
     * 
     */
    uid?: string;
}

/**
 * Check if a given object implements the DeleteTodoCommand interface.
 */
export function instanceOfDeleteTodoCommand(value: object): value is DeleteTodoCommand {
    return true;
}

export function DeleteTodoCommandFromJSON(json: any): DeleteTodoCommand {
    return DeleteTodoCommandFromJSONTyped(json, false);
}

export function DeleteTodoCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTodoCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function DeleteTodoCommandToJSON(json: any): DeleteTodoCommand {
    return DeleteTodoCommandToJSONTyped(json, false);
}

export function DeleteTodoCommandToJSONTyped(value?: DeleteTodoCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

