/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileMetadataDto
 */
export interface FileMetadataDto {
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDto
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDto
     */
    fileName?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FileMetadataDto
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof FileMetadataDto
     */
    fileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDto
     */
    fileHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDto
     */
    uploadTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileMetadataDto
     */
    fileType?: string | null;
}

/**
 * Check if a given object implements the FileMetadataDto interface.
 */
export function instanceOfFileMetadataDto(value: object): value is FileMetadataDto {
    return true;
}

export function FileMetadataDtoFromJSON(json: any): FileMetadataDto {
    return FileMetadataDtoFromJSONTyped(json, false);
}

export function FileMetadataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMetadataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'fileHash': json['fileHash'] == null ? undefined : json['fileHash'],
        'uploadTime': json['uploadTime'] == null ? undefined : json['uploadTime'],
        'fileType': json['fileType'] == null ? undefined : json['fileType'],
    };
}

export function FileMetadataDtoToJSON(json: any): FileMetadataDto {
    return FileMetadataDtoToJSONTyped(json, false);
}

export function FileMetadataDtoToJSONTyped(value?: FileMetadataDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'fileName': value['fileName'],
        'tags': value['tags'],
        'fileSize': value['fileSize'],
        'fileHash': value['fileHash'],
        'uploadTime': value['uploadTime'],
        'fileType': value['fileType'],
    };
}

