/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileScope = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type FileScope = typeof FileScope[keyof typeof FileScope];


export function instanceOfFileScope(value: any): boolean {
    for (const key in FileScope) {
        if (Object.prototype.hasOwnProperty.call(FileScope, key)) {
            if (FileScope[key as keyof typeof FileScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileScopeFromJSON(json: any): FileScope {
    return FileScopeFromJSONTyped(json, false);
}

export function FileScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileScope {
    return json as FileScope;
}

export function FileScopeToJSON(value?: FileScope | null): any {
    return value as any;
}

export function FileScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): FileScope {
    return value as FileScope;
}

