/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagDto } from './TagDto';
import {
    TagDtoFromJSON,
    TagDtoFromJSONTyped,
    TagDtoToJSON,
    TagDtoToJSONTyped,
} from './TagDto';

/**
 * 
 * @export
 * @interface FileDto
 */
export interface FileDto {
    /**
     * 
     */
    uid?: string;
    /**
     * 
     */
    fileName?: string | null;
    /**
     * 
     */
    tags?: Array<TagDto> | null;
    /**
     * 
     */
    fileSize?: number;
    /**
     * 
     */
    fileHash?: string | null;
    /**
     * 
     */
    uploadTime?: string | null;
    /**
     * 
     */
    fileType?: string | null;
    /**
     * 
     */
    fileIntroduction?: string | null;
}

/**
 * Check if a given object implements the FileDto interface.
 */
export function instanceOfFileDto(value: object): value is FileDto {
    return true;
}

export function FileDtoFromJSON(json: any): FileDto {
    return FileDtoFromJSONTyped(json, false);
}

export function FileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'fileName': json['fileName'] === undefined ? undefined : json['fileName'] === null ? null : json['fileName'],
        'tags': json['tags'] === undefined ? undefined : json['tags'] === null ? null : ((json['tags'] as Array<any>).map(TagDtoFromJSON)),
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'fileHash': json['fileHash'] === undefined ? undefined : json['fileHash'] === null ? null : json['fileHash'],
        'uploadTime': json['uploadTime'] === undefined ? undefined : json['uploadTime'] === null ? null : json['uploadTime'],
        'fileType': json['fileType'] === undefined ? undefined : json['fileType'] === null ? null : json['fileType'],
        'fileIntroduction': json['fileIntroduction'] === undefined ? undefined : json['fileIntroduction'] === null ? null : json['fileIntroduction'],
    };
}

export function FileDtoToJSON(json: any): FileDto {
    return FileDtoToJSONTyped(json, false);
}

export function FileDtoToJSONTyped(value?: FileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'fileName': value['fileName'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagDtoToJSON)),
        'fileSize': value['fileSize'],
        'fileHash': value['fileHash'],
        'uploadTime': value['uploadTime'],
        'fileType': value['fileType'],
        'fileIntroduction': value['fileIntroduction'],
    };
}

