/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type FileStatus = typeof FileStatus[keyof typeof FileStatus];


export function instanceOfFileStatus(value: any): boolean {
    for (const key in FileStatus) {
        if (Object.prototype.hasOwnProperty.call(FileStatus, key)) {
            if (FileStatus[key as keyof typeof FileStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileStatusFromJSON(json: any): FileStatus {
    return FileStatusFromJSONTyped(json, false);
}

export function FileStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileStatus {
    return json as FileStatus;
}

export function FileStatusToJSON(value?: FileStatus | null): any {
    return value as any;
}

export function FileStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): FileStatus {
    return value as FileStatus;
}

