/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileDto } from './FileDto';
import {
    FileDtoFromJSON,
    FileDtoFromJSONTyped,
    FileDtoToJSON,
    FileDtoToJSONTyped,
} from './FileDto';

/**
 * 
 * @export
 * @interface FileDtoPageResult
 */
export interface FileDtoPageResult {
    /**
     * 
     * @type {Array<FileDto>}
     * @memberof FileDtoPageResult
     */
    items?: Array<FileDto> | null;
    /**
     * 
     * @type {number}
     * @memberof FileDtoPageResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FileDtoPageResult
     */
    pageSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FileDtoPageResult
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the FileDtoPageResult interface.
 */
export function instanceOfFileDtoPageResult(value: object): value is FileDtoPageResult {
    return true;
}

export function FileDtoPageResultFromJSON(json: any): FileDtoPageResult {
    return FileDtoPageResultFromJSONTyped(json, false);
}

export function FileDtoPageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileDtoPageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(FileDtoFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function FileDtoPageResultToJSON(json: any): FileDtoPageResult {
    return FileDtoPageResultToJSONTyped(json, false);
}

export function FileDtoPageResultToJSONTyped(value?: FileDtoPageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(FileDtoToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'hasMore': value['hasMore'],
    };
}

