/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileOrder = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type FileOrder = typeof FileOrder[keyof typeof FileOrder];


export function instanceOfFileOrder(value: any): boolean {
    for (const key in FileOrder) {
        if (Object.prototype.hasOwnProperty.call(FileOrder, key)) {
            if (FileOrder[key as keyof typeof FileOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileOrderFromJSON(json: any): FileOrder {
    return FileOrderFromJSONTyped(json, false);
}

export function FileOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileOrder {
    return json as FileOrder;
}

export function FileOrderToJSON(value?: FileOrder | null): any {
    return value as any;
}

export function FileOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): FileOrder {
    return value as FileOrder;
}

