/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileDto } from './FileDto';
import {
    FileDtoFromJSON,
    FileDtoFromJSONTyped,
    FileDtoToJSON,
    FileDtoToJSONTyped,
} from './FileDto';

/**
 * 
 * @export
 * @interface OverviewDto
 */
export interface OverviewDto {
    /**
     * 
     * @type {number}
     * @memberof OverviewDto
     */
    draftCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OverviewDto
     */
    scheduledCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OverviewDto
     */
    publishedCount?: number;
    /**
     * 
     * @type {Array<FileDto>}
     * @memberof OverviewDto
     */
    recentFiles?: Array<FileDto> | null;
}

/**
 * Check if a given object implements the OverviewDto interface.
 */
export function instanceOfOverviewDto(value: object): value is OverviewDto {
    return true;
}

export function OverviewDtoFromJSON(json: any): OverviewDto {
    return OverviewDtoFromJSONTyped(json, false);
}

export function OverviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverviewDto {
    if (json == null) {
        return json;
    }
    return {
        
        'draftCount': json['draftCount'] == null ? undefined : json['draftCount'],
        'scheduledCount': json['scheduledCount'] == null ? undefined : json['scheduledCount'],
        'publishedCount': json['publishedCount'] == null ? undefined : json['publishedCount'],
        'recentFiles': json['recentFiles'] == null ? undefined : ((json['recentFiles'] as Array<any>).map(FileDtoFromJSON)),
    };
}

export function OverviewDtoToJSON(json: any): OverviewDto {
    return OverviewDtoToJSONTyped(json, false);
}

export function OverviewDtoToJSONTyped(value?: OverviewDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'draftCount': value['draftCount'],
        'scheduledCount': value['scheduledCount'],
        'publishedCount': value['publishedCount'],
        'recentFiles': value['recentFiles'] == null ? undefined : ((value['recentFiles'] as Array<any>).map(FileDtoToJSON)),
    };
}

