/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishFileCommand
 */
export interface PublishFileCommand {
    /**
     * 
     */
    uid?: string;
}

/**
 * Check if a given object implements the PublishFileCommand interface.
 */
export function instanceOfPublishFileCommand(value: object): value is PublishFileCommand {
    return true;
}

export function PublishFileCommandFromJSON(json: any): PublishFileCommand {
    return PublishFileCommandFromJSONTyped(json, false);
}

export function PublishFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function PublishFileCommandToJSON(json: any): PublishFileCommand {
    return PublishFileCommandToJSONTyped(json, false);
}

export function PublishFileCommandToJSONTyped(value?: PublishFileCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

