/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledBlogCommand
 */
export interface ScheduledBlogCommand {
    /**
     * 
     * @type {string}
     * @memberof ScheduledBlogCommand
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledBlogCommand
     */
    scheduledAt?: string;
}

/**
 * Check if a given object implements the ScheduledBlogCommand interface.
 */
export function instanceOfScheduledBlogCommand(value: object): value is ScheduledBlogCommand {
    return true;
}

export function ScheduledBlogCommandFromJSON(json: any): ScheduledBlogCommand {
    return ScheduledBlogCommandFromJSONTyped(json, false);
}

export function ScheduledBlogCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledBlogCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'scheduledAt': json['scheduledAt'] == null ? undefined : json['scheduledAt'],
    };
}

export function ScheduledBlogCommandToJSON(json: any): ScheduledBlogCommand {
    return ScheduledBlogCommandToJSONTyped(json, false);
}

export function ScheduledBlogCommandToJSONTyped(value?: ScheduledBlogCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'scheduledAt': value['scheduledAt'],
    };
}

