/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledFileCommand
 */
export interface ScheduledFileCommand {
    /**
     * 
     * @type {string}
     * @memberof ScheduledFileCommand
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof ScheduledFileCommand
     */
    scheduledAt?: string | null;
}

/**
 * Check if a given object implements the ScheduledFileCommand interface.
 */
export function instanceOfScheduledFileCommand(value: object): value is ScheduledFileCommand {
    return true;
}

export function ScheduledFileCommandFromJSON(json: any): ScheduledFileCommand {
    return ScheduledFileCommandFromJSONTyped(json, false);
}

export function ScheduledFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'scheduledAt': json['scheduledAt'] == null ? undefined : json['scheduledAt'],
    };
}

export function ScheduledFileCommandToJSON(json: any): ScheduledFileCommand {
    return ScheduledFileCommandToJSONTyped(json, false);
}

export function ScheduledFileCommandToJSONTyped(value?: ScheduledFileCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'scheduledAt': value['scheduledAt'],
    };
}

