/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionDto
 */
export interface SubscriptionDto {
    /**
     * 
     */
    aliasName?: string | null;
    /**
     * 
     */
    subscriptionLink?: string | null;
    /**
     * 
     */
    subscriptionPlatform?: string | null;
    /**
     * 
     */
    subscriptionIcon?: string;
}

/**
 * Check if a given object implements the SubscriptionDto interface.
 */
export function instanceOfSubscriptionDto(value: object): value is SubscriptionDto {
    return true;
}

export function SubscriptionDtoFromJSON(json: any): SubscriptionDto {
    return SubscriptionDtoFromJSONTyped(json, false);
}

export function SubscriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'aliasName': json['aliasName'] === undefined ? undefined : json['aliasName'] === null ? null : json['aliasName'],
        'subscriptionLink': json['subscriptionLink'] === undefined ? undefined : json['subscriptionLink'] === null ? null : json['subscriptionLink'],
        'subscriptionPlatform': json['subscriptionPlatform'] === undefined ? undefined : json['subscriptionPlatform'] === null ? null : json['subscriptionPlatform'],
        'subscriptionIcon': json['subscriptionIcon'] == null ? undefined : json['subscriptionIcon'],
    };
}

export function SubscriptionDtoToJSON(json: any): SubscriptionDto {
    return SubscriptionDtoToJSONTyped(json, false);
}

export function SubscriptionDtoToJSONTyped(value?: SubscriptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliasName': value['aliasName'],
        'subscriptionLink': value['subscriptionLink'],
        'subscriptionPlatform': value['subscriptionPlatform'],
        'subscriptionIcon': value['subscriptionIcon'],
    };
}

