/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagDto
 */
export interface TagDto {
    /**
     * 
     */
    uid?: string | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    aliasName?: string | null;
    /**
     * 
     */
    isCategory?: boolean;
}

/**
 * Check if a given object implements the TagDto interface.
 */
export function instanceOfTagDto(value: object): value is TagDto {
    return true;
}

export function TagDtoFromJSON(json: any): TagDto {
    return TagDtoFromJSONTyped(json, false);
}

export function TagDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] === undefined ? undefined : json['uid'] === null ? null : json['uid'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'aliasName': json['aliasName'] === undefined ? undefined : json['aliasName'] === null ? null : json['aliasName'],
        'isCategory': json['isCategory'] == null ? undefined : json['isCategory'],
    };
}

export function TagDtoToJSON(json: any): TagDto {
    return TagDtoToJSONTyped(json, false);
}

export function TagDtoToJSONTyped(value?: TagDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'name': value['name'],
        'aliasName': value['aliasName'],
        'isCategory': value['isCategory'],
    };
}

