/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagDto } from './TagDto';
import {
    TagDtoFromJSON,
    TagDtoFromJSONTyped,
    TagDtoToJSON,
    TagDtoToJSONTyped,
} from './TagDto';

/**
 * 
 * @export
 * @interface TagDtoPageResult
 */
export interface TagDtoPageResult {
    /**
     * 
     * @type {Array<TagDto>}
     * @memberof TagDtoPageResult
     */
    items?: Array<TagDto> | null;
    /**
     * 
     * @type {number}
     * @memberof TagDtoPageResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TagDtoPageResult
     */
    pageSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TagDtoPageResult
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the TagDtoPageResult interface.
 */
export function instanceOfTagDtoPageResult(value: object): value is TagDtoPageResult {
    return true;
}

export function TagDtoPageResultFromJSON(json: any): TagDtoPageResult {
    return TagDtoPageResultFromJSONTyped(json, false);
}

export function TagDtoPageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagDtoPageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TagDtoFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function TagDtoPageResultToJSON(json: any): TagDtoPageResult {
    return TagDtoPageResultToJSONTyped(json, false);
}

export function TagDtoPageResultToJSONTyped(value?: TagDtoPageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TagDtoToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'hasMore': value['hasMore'],
    };
}

