/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoDto } from './TodoDto';
import {
    TodoDtoFromJSON,
    TodoDtoFromJSONTyped,
    TodoDtoToJSON,
    TodoDtoToJSONTyped,
} from './TodoDto';

/**
 * 
 * @export
 * @interface TodoDtoPageResult
 */
export interface TodoDtoPageResult {
    /**
     * 
     * @type {Array<TodoDto>}
     * @memberof TodoDtoPageResult
     */
    items?: Array<TodoDto> | null;
    /**
     * 
     * @type {number}
     * @memberof TodoDtoPageResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TodoDtoPageResult
     */
    pageSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TodoDtoPageResult
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the TodoDtoPageResult interface.
 */
export function instanceOfTodoDtoPageResult(value: object): value is TodoDtoPageResult {
    return true;
}

export function TodoDtoPageResultFromJSON(json: any): TodoDtoPageResult {
    return TodoDtoPageResultFromJSONTyped(json, false);
}

export function TodoDtoPageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoDtoPageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TodoDtoFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
    };
}

export function TodoDtoPageResultToJSON(json: any): TodoDtoPageResult {
    return TodoDtoPageResultToJSONTyped(json, false);
}

export function TodoDtoPageResultToJSONTyped(value?: TodoDtoPageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TodoDtoToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'hasMore': value['hasMore'],
    };
}

