/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoDto
 */
export interface TodoDto {
    /**
     * 
     */
    uid?: string;
    /**
     * 
     */
    ftid?: string | null;
    /**
     * 
     */
    desc?: string | null;
    /**
     * 
     */
    status?: string | null;
    /**
     * 
     */
    createdAt?: string;
    /**
     * 
     */
    completedAt?: string | null;
    /**
     * 
     */
    priority?: number;
    /**
     * 
     */
    todoList?: Array<TodoDto> | null;
    /**
     * 
     */
    hasChildren?: boolean;
}

/**
 * Check if a given object implements the TodoDto interface.
 */
export function instanceOfTodoDto(value: object): value is TodoDto {
    return true;
}

export function TodoDtoFromJSON(json: any): TodoDto {
    return TodoDtoFromJSONTyped(json, false);
}

export function TodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'ftid': json['ftid'] === undefined ? undefined : json['ftid'] === null ? null : json['ftid'],
        'desc': json['desc'] === undefined ? undefined : json['desc'] === null ? null : json['desc'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'completedAt': json['completedAt'] === undefined ? undefined : json['completedAt'] === null ? null : json['completedAt'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'todoList': json['todoList'] === undefined ? undefined : json['todoList'] === null ? null : ((json['todoList'] as Array<any>).map(TodoDtoFromJSON)),
        'hasChildren': json['hasChildren'] == null ? undefined : json['hasChildren'],
    };
}

export function TodoDtoToJSON(json: any): TodoDto {
    return TodoDtoToJSONTyped(json, false);
}

export function TodoDtoToJSONTyped(value?: TodoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'ftid': value['ftid'],
        'desc': value['desc'],
        'status': value['status'],
        'createdAt': value['createdAt'],
        'completedAt': value['completedAt'],
        'priority': value['priority'],
        'todoList': value['todoList'] == null ? undefined : ((value['todoList'] as Array<any>).map(TodoDtoToJSON)),
        'hasChildren': value['hasChildren'],
    };
}

