/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTagCommand
 */
export interface UpdateTagCommand {
    /**
     * 
     */
    uid?: string;
    /**
     * 
     */
    tagName?: string | null;
    /**
     * 
     */
    aliasName?: string | null;
    /**
     * 
     */
    isCategory?: boolean;
}

/**
 * Check if a given object implements the UpdateTagCommand interface.
 */
export function instanceOfUpdateTagCommand(value: object): value is UpdateTagCommand {
    return true;
}

export function UpdateTagCommandFromJSON(json: any): UpdateTagCommand {
    return UpdateTagCommandFromJSONTyped(json, false);
}

export function UpdateTagCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTagCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'tagName': json['tagName'] === undefined ? undefined : json['tagName'] === null ? null : json['tagName'],
        'aliasName': json['aliasName'] === undefined ? undefined : json['aliasName'] === null ? null : json['aliasName'],
        'isCategory': json['isCategory'] == null ? undefined : json['isCategory'],
    };
}

export function UpdateTagCommandToJSON(json: any): UpdateTagCommand {
    return UpdateTagCommandToJSONTyped(json, false);
}

export function UpdateTagCommandToJSONTyped(value?: UpdateTagCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'tagName': value['tagName'],
        'aliasName': value['aliasName'],
        'isCategory': value['isCategory'],
    };
}

