/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFileTagCommand
 */
export interface UpdateFileTagCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateFileTagCommand
     */
    uid?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateFileTagCommand
     */
    tags?: Array<string> | null;
}

/**
 * Check if a given object implements the UpdateFileTagCommand interface.
 */
export function instanceOfUpdateFileTagCommand(value: object): value is UpdateFileTagCommand {
    return true;
}

export function UpdateFileTagCommandFromJSON(json: any): UpdateFileTagCommand {
    return UpdateFileTagCommandFromJSONTyped(json, false);
}

export function UpdateFileTagCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFileTagCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function UpdateFileTagCommandToJSON(json: any): UpdateFileTagCommand {
    return UpdateFileTagCommandToJSONTyped(json, false);
}

export function UpdateFileTagCommandToJSONTyped(value?: UpdateFileTagCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'tags': value['tags'],
    };
}

