/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoStatus } from './TodoStatus';
import {
    TodoStatusFromJSON,
    TodoStatusFromJSONTyped,
    TodoStatusToJSON,
    TodoStatusToJSONTyped,
} from './TodoStatus';

/**
 * 
 * @export
 * @interface UpdateTodoCommand
 */
export interface UpdateTodoCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoCommand
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoCommand
     */
    desc?: string | null;
    /**
     * 
     * @type {TodoStatus}
     * @memberof UpdateTodoCommand
     */
    status?: TodoStatus;
    /**
     * 
     * @type {number}
     * @memberof UpdateTodoCommand
     */
    priority?: number;
}



/**
 * Check if a given object implements the UpdateTodoCommand interface.
 */
export function instanceOfUpdateTodoCommand(value: object): value is UpdateTodoCommand {
    return true;
}

export function UpdateTodoCommandFromJSON(json: any): UpdateTodoCommand {
    return UpdateTodoCommandFromJSONTyped(json, false);
}

export function UpdateTodoCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTodoCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'status': json['status'] == null ? undefined : TodoStatusFromJSON(json['status']),
        'priority': json['priority'] == null ? undefined : json['priority'],
    };
}

export function UpdateTodoCommandToJSON(json: any): UpdateTodoCommand {
    return UpdateTodoCommandToJSONTyped(json, false);
}

export function UpdateTodoCommandToJSONTyped(value?: UpdateTodoCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'desc': value['desc'],
        'status': TodoStatusToJSON(value['status']),
        'priority': value['priority'],
    };
}

