/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccountDto,
    AccountDtoFromJSON,
    AccountDtoToJSON,
} from '../models/AccountDto';
import {
    type AccountProfile,
    AccountProfileFromJSON,
    AccountProfileToJSON,
} from '../models/AccountProfile';
import {
    type CreateAccountCommand,
    CreateAccountCommandFromJSON,
    CreateAccountCommandToJSON,
} from '../models/CreateAccountCommand';
import {
    type LoginCommand,
    LoginCommandFromJSON,
    LoginCommandToJSON,
} from '../models/LoginCommand';
import {
    type SubscriptionDto,
    SubscriptionDtoFromJSON,
    SubscriptionDtoToJSON,
} from '../models/SubscriptionDto';

export interface ApiAccountAvatarPatchRequest {
    /**
     * 
     */
    avatar?: Blob;
}

export interface ApiAccountLoginPostRequest {
    /**
     * 
     */
    loginCommand?: LoginCommand;
}

export interface ApiAccountPostRequest {
    /**
     * 
     */
    createAccountCommand?: CreateAccountCommand;
}

export interface ApiAccountProfilePatchRequest {
    /**
     * 
     */
    accountProfile?: AccountProfile;
}

export interface ApiAccountSubscriptionsPutRequest {
    /**
     * 
     */
    subscriptionDto?: Array<SubscriptionDto>;
}

/**
 * AccountApi - interface
 * 
 * @export
 * @interface AccountApiInterface
 */
export interface AccountApiInterface {
    /**
     * Creates request options for apiAccountAvatarPatch without sending the request
     * @param {Blob} [avatar] 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountAvatarPatchRequestOpts(requestParameters: ApiAccountAvatarPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {Blob} [avatar] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountAvatarPatchRaw(requestParameters: ApiAccountAvatarPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiAccountAvatarPatch(requestParameters: ApiAccountAvatarPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiAccountDelete without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountDeleteRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountDeleteRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiAccountDelete(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for apiAccountGet without sending the request
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDto>>;

    /**
     */
    apiAccountGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDto>;

    /**
     * Creates request options for apiAccountLoginPost without sending the request
     * @param {LoginCommand} [loginCommand] 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountLoginPostRequestOpts(requestParameters: ApiAccountLoginPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {LoginCommand} [loginCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountLoginPostRaw(requestParameters: ApiAccountLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiAccountLoginPost(requestParameters: ApiAccountLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiAccountPost without sending the request
     * @param {CreateAccountCommand} [createAccountCommand] 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountPostRequestOpts(requestParameters: ApiAccountPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateAccountCommand} [createAccountCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountPostRaw(requestParameters: ApiAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiAccountPost(requestParameters: ApiAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiAccountProfilePatch without sending the request
     * @param {AccountProfile} [accountProfile] 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountProfilePatchRequestOpts(requestParameters: ApiAccountProfilePatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {AccountProfile} [accountProfile] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountProfilePatchRaw(requestParameters: ApiAccountProfilePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiAccountProfilePatch(requestParameters: ApiAccountProfilePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiAccountSubscriptionsPut without sending the request
     * @param {Array<SubscriptionDto>} [subscriptionDto] 
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountSubscriptionsPutRequestOpts(requestParameters: ApiAccountSubscriptionsPutRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {Array<SubscriptionDto>} [subscriptionDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    apiAccountSubscriptionsPutRaw(requestParameters: ApiAccountSubscriptionsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiAccountSubscriptionsPut(requestParameters: ApiAccountSubscriptionsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI implements AccountApiInterface {

    /**
     * Creates request options for apiAccountAvatarPatch without sending the request
     */
    async apiAccountAvatarPatchRequestOpts(requestParameters: ApiAccountAvatarPatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['avatar'] != null) {
            formParams.append('avatar', requestParameters['avatar'] as any);
        }


        let urlPath = `/api/Account/avatar`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async apiAccountAvatarPatchRaw(requestParameters: ApiAccountAvatarPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiAccountAvatarPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiAccountAvatarPatch(requestParameters: ApiAccountAvatarPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAccountAvatarPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountDelete without sending the request
     */
    async apiAccountDeleteRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Account`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiAccountDeleteRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiAccountDeleteRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiAccountDelete(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAccountDeleteRaw(initOverrides);
    }

    /**
     * Creates request options for apiAccountGet without sending the request
     */
    async apiAccountGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Account`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiAccountGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountDto>> {
        const requestOptions = await this.apiAccountGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAccountGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountDto> {
        const response = await this.apiAccountGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountLoginPost without sending the request
     */
    async apiAccountLoginPostRequestOpts(requestParameters: ApiAccountLoginPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Account/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginCommandToJSON(requestParameters['loginCommand']),
        };
    }

    /**
     */
    async apiAccountLoginPostRaw(requestParameters: ApiAccountLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiAccountLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiAccountLoginPost(requestParameters: ApiAccountLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAccountLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountPost without sending the request
     */
    async apiAccountPostRequestOpts(requestParameters: ApiAccountPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Account`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAccountCommandToJSON(requestParameters['createAccountCommand']),
        };
    }

    /**
     */
    async apiAccountPostRaw(requestParameters: ApiAccountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiAccountPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiAccountPost(requestParameters: ApiAccountPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAccountPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountProfilePatch without sending the request
     */
    async apiAccountProfilePatchRequestOpts(requestParameters: ApiAccountProfilePatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Account/profile`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AccountProfileToJSON(requestParameters['accountProfile']),
        };
    }

    /**
     */
    async apiAccountProfilePatchRaw(requestParameters: ApiAccountProfilePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiAccountProfilePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiAccountProfilePatch(requestParameters: ApiAccountProfilePatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAccountProfilePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiAccountSubscriptionsPut without sending the request
     */
    async apiAccountSubscriptionsPutRequestOpts(requestParameters: ApiAccountSubscriptionsPutRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Account/subscriptions`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['subscriptionDto']!.map(SubscriptionDtoToJSON),
        };
    }

    /**
     */
    async apiAccountSubscriptionsPutRaw(requestParameters: ApiAccountSubscriptionsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiAccountSubscriptionsPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiAccountSubscriptionsPut(requestParameters: ApiAccountSubscriptionsPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiAccountSubscriptionsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
