/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CorpusDtoPageResult,
    CorpusDtoPageResultFromJSON,
    CorpusDtoPageResultToJSON,
} from '../models/CorpusDtoPageResult';
import {
    type CreateCorpusCommand,
    CreateCorpusCommandFromJSON,
    CreateCorpusCommandToJSON,
} from '../models/CreateCorpusCommand';
import {
    type DeleteCorepusCommand,
    DeleteCorepusCommandFromJSON,
    DeleteCorepusCommandToJSON,
} from '../models/DeleteCorepusCommand';

export interface ApiCorpusDeleteRequest {
    deleteCorepusCommand?: DeleteCorepusCommand;
}

export interface ApiCorpusGetRequest {
    uID?: string;
    content?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiCorpusPostRequest {
    createCorpusCommand?: CreateCorpusCommand;
}

/**
 * CorpusApi - interface
 * 
 * @export
 * @interface CorpusApiInterface
 */
export interface CorpusApiInterface {
    /**
     * Creates request options for apiCorpusDelete without sending the request
     * @param {DeleteCorepusCommand} [deleteCorepusCommand] 
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusDeleteRequestOpts(requestParameters: ApiCorpusDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {DeleteCorepusCommand} [deleteCorepusCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusDeleteRaw(requestParameters: ApiCorpusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiCorpusDelete(requestParameters: ApiCorpusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for apiCorpusGet without sending the request
     * @param {string} [uID] 
     * @param {string} [content] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusGetRequestOpts(requestParameters: ApiCorpusGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {string} [content] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusGetRaw(requestParameters: ApiCorpusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorpusDtoPageResult>>;

    /**
     */
    apiCorpusGet(requestParameters: ApiCorpusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorpusDtoPageResult>;

    /**
     * Creates request options for apiCorpusPost without sending the request
     * @param {CreateCorpusCommand} [createCorpusCommand] 
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusPostRequestOpts(requestParameters: ApiCorpusPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateCorpusCommand} [createCorpusCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusPostRaw(requestParameters: ApiCorpusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiCorpusPost(requestParameters: ApiCorpusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiCorpusRandomGet without sending the request
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusRandomGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusRandomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiCorpusRandomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class CorpusApi extends runtime.BaseAPI implements CorpusApiInterface {

    /**
     * Creates request options for apiCorpusDelete without sending the request
     */
    async apiCorpusDeleteRequestOpts(requestParameters: ApiCorpusDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Corpus`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteCorepusCommandToJSON(requestParameters['deleteCorepusCommand']),
        };
    }

    /**
     */
    async apiCorpusDeleteRaw(requestParameters: ApiCorpusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiCorpusDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCorpusDelete(requestParameters: ApiCorpusDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCorpusDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiCorpusGet without sending the request
     */
    async apiCorpusGetRequestOpts(requestParameters: ApiCorpusGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['Content'] = requestParameters['content'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Corpus`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCorpusGetRaw(requestParameters: ApiCorpusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CorpusDtoPageResult>> {
        const requestOptions = await this.apiCorpusGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CorpusDtoPageResultFromJSON(jsonValue));
    }

    /**
     */
    async apiCorpusGet(requestParameters: ApiCorpusGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CorpusDtoPageResult> {
        const response = await this.apiCorpusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCorpusPost without sending the request
     */
    async apiCorpusPostRequestOpts(requestParameters: ApiCorpusPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Corpus`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCorpusCommandToJSON(requestParameters['createCorpusCommand']),
        };
    }

    /**
     */
    async apiCorpusPostRaw(requestParameters: ApiCorpusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiCorpusPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiCorpusPost(requestParameters: ApiCorpusPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiCorpusPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCorpusRandomGet without sending the request
     */
    async apiCorpusRandomGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Corpus/random`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCorpusRandomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiCorpusRandomGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiCorpusRandomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiCorpusRandomGetRaw(initOverrides);
        return await response.value();
    }

}
