/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CorpusDto,
    CorpusDtoFromJSON,
    CorpusDtoToJSON,
} from '../models/CorpusDto';
import {
    type CreateCorpusCommand,
    CreateCorpusCommandFromJSON,
    CreateCorpusCommandToJSON,
} from '../models/CreateCorpusCommand';
import {
    type DeleteCorepusCommand,
    DeleteCorepusCommandFromJSON,
    DeleteCorepusCommandToJSON,
} from '../models/DeleteCorepusCommand';

export interface ApiCorpusDeleteRequest {
    /**
     * 
     */
    deleteCorepusCommand?: DeleteCorepusCommand;
}

export interface ApiCorpusPostRequest {
    /**
     * 
     */
    createCorpusCommand?: CreateCorpusCommand;
}

export interface ApiCorpusSearchGetRequest {
    /**
     * 
     */
    uID?: string;
    /**
     * 
     */
    content?: string;
}

/**
 * CorpusApi - interface
 * 
 * @export
 * @interface CorpusApiInterface
 */
export interface CorpusApiInterface {
    /**
     * Creates request options for apiCorpusDelete without sending the request
     * @param {DeleteCorepusCommand} [deleteCorepusCommand] 
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusDeleteRequestOpts(requestParameters: ApiCorpusDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {DeleteCorepusCommand} [deleteCorepusCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusDeleteRaw(requestParameters: ApiCorpusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiCorpusDelete(requestParameters: ApiCorpusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for apiCorpusGet without sending the request
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CorpusDto>>>;

    /**
     */
    apiCorpusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CorpusDto>>;

    /**
     * Creates request options for apiCorpusPost without sending the request
     * @param {CreateCorpusCommand} [createCorpusCommand] 
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusPostRequestOpts(requestParameters: ApiCorpusPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateCorpusCommand} [createCorpusCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusPostRaw(requestParameters: ApiCorpusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiCorpusPost(requestParameters: ApiCorpusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiCorpusRandomGet without sending the request
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusRandomGetRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusRandomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiCorpusRandomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiCorpusSearchGet without sending the request
     * @param {string} [uID] 
     * @param {string} [content] 
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusSearchGetRequestOpts(requestParameters: ApiCorpusSearchGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {string} [content] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CorpusApiInterface
     */
    apiCorpusSearchGetRaw(requestParameters: ApiCorpusSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CorpusDto>>>;

    /**
     */
    apiCorpusSearchGet(requestParameters: ApiCorpusSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CorpusDto>>;

}

/**
 * 
 */
export class CorpusApi extends runtime.BaseAPI implements CorpusApiInterface {

    /**
     * Creates request options for apiCorpusDelete without sending the request
     */
    async apiCorpusDeleteRequestOpts(requestParameters: ApiCorpusDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Corpus`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteCorepusCommandToJSON(requestParameters['deleteCorepusCommand']),
        };
    }

    /**
     */
    async apiCorpusDeleteRaw(requestParameters: ApiCorpusDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiCorpusDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCorpusDelete(requestParameters: ApiCorpusDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCorpusDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiCorpusGet without sending the request
     */
    async apiCorpusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Corpus`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCorpusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CorpusDto>>> {
        const requestOptions = await this.apiCorpusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CorpusDtoFromJSON));
    }

    /**
     */
    async apiCorpusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CorpusDto>> {
        const response = await this.apiCorpusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCorpusPost without sending the request
     */
    async apiCorpusPostRequestOpts(requestParameters: ApiCorpusPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Corpus`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCorpusCommandToJSON(requestParameters['createCorpusCommand']),
        };
    }

    /**
     */
    async apiCorpusPostRaw(requestParameters: ApiCorpusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiCorpusPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiCorpusPost(requestParameters: ApiCorpusPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiCorpusPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCorpusRandomGet without sending the request
     */
    async apiCorpusRandomGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Corpus/random`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCorpusRandomGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiCorpusRandomGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiCorpusRandomGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiCorpusRandomGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiCorpusSearchGet without sending the request
     */
    async apiCorpusSearchGetRequestOpts(requestParameters: ApiCorpusSearchGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        if (requestParameters['content'] != null) {
            queryParameters['Content'] = requestParameters['content'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Corpus/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiCorpusSearchGetRaw(requestParameters: ApiCorpusSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CorpusDto>>> {
        const requestOptions = await this.apiCorpusSearchGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CorpusDtoFromJSON));
    }

    /**
     */
    async apiCorpusSearchGet(requestParameters: ApiCorpusSearchGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CorpusDto>> {
        const response = await this.apiCorpusSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
