/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DeleteFileCommand,
    DeleteFileCommandFromJSON,
    DeleteFileCommandToJSON,
} from '../models/DeleteFileCommand';
import {
    type FileDto,
    FileDtoFromJSON,
    FileDtoToJSON,
} from '../models/FileDto';
import {
    type UpdateFileTagCommand,
    UpdateFileTagCommandFromJSON,
    UpdateFileTagCommandToJSON,
} from '../models/UpdateFileTagCommand';

export interface ApiFileDeleteRequest {
    deleteFileCommand?: DeleteFileCommand;
}

export interface ApiFileDownloadGetRequest {
    uID?: string;
}

export interface ApiFileGetRequest {
    uID?: string;
    title?: string;
}

export interface ApiFilePatchRequest {
    uID?: string;
    file?: Blob;
}

export interface ApiFilePreviewGetRequest {
    uID?: string;
}

export interface ApiFileTagPatchRequest {
    updateFileTagCommand?: UpdateFileTagCommand;
}

export interface ApiFileUploadPostRequest {
    file?: Array<Blob>;
}

/**
 * FileApi - interface
 * 
 * @export
 * @interface FileApiInterface
 */
export interface FileApiInterface {
    /**
     * Creates request options for apiFileDelete without sending the request
     * @param {DeleteFileCommand} [deleteFileCommand] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileDeleteRequestOpts(requestParameters: ApiFileDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {DeleteFileCommand} [deleteFileCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileDeleteRaw(requestParameters: ApiFileDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiFileDelete(requestParameters: ApiFileDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for apiFileDownloadGet without sending the request
     * @param {string} [uID] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileDownloadGetRequestOpts(requestParameters: ApiFileDownloadGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileDownloadGetRaw(requestParameters: ApiFileDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     */
    apiFileDownloadGet(requestParameters: ApiFileDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for apiFileGet without sending the request
     * @param {string} [uID] 
     * @param {string} [title] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileGetRequestOpts(requestParameters: ApiFileGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {string} [title] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileGetRaw(requestParameters: ApiFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileDto>>>;

    /**
     */
    apiFileGet(requestParameters: ApiFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileDto>>;

    /**
     * Creates request options for apiFilePatch without sending the request
     * @param {string} [uID] 
     * @param {Blob} [file] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFilePatchRequestOpts(requestParameters: ApiFilePatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {Blob} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFilePatchRaw(requestParameters: ApiFilePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiFilePatch(requestParameters: ApiFilePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiFilePreviewGet without sending the request
     * @param {string} [uID] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFilePreviewGetRequestOpts(requestParameters: ApiFilePreviewGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFilePreviewGetRaw(requestParameters: ApiFilePreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     */
    apiFilePreviewGet(requestParameters: ApiFilePreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

    /**
     * Creates request options for apiFileTagPatch without sending the request
     * @param {UpdateFileTagCommand} [updateFileTagCommand] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileTagPatchRequestOpts(requestParameters: ApiFileTagPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {UpdateFileTagCommand} [updateFileTagCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileTagPatchRaw(requestParameters: ApiFileTagPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiFileTagPatch(requestParameters: ApiFileTagPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiFileUploadPost without sending the request
     * @param {Array<Blob>} [file] 
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileUploadPostRequestOpts(requestParameters: ApiFileUploadPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {Array<Blob>} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FileApiInterface
     */
    apiFileUploadPostRaw(requestParameters: ApiFileUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     */
    apiFileUploadPost(requestParameters: ApiFileUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

}

/**
 * 
 */
export class FileApi extends runtime.BaseAPI implements FileApiInterface {

    /**
     * Creates request options for apiFileDelete without sending the request
     */
    async apiFileDeleteRequestOpts(requestParameters: ApiFileDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/File`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteFileCommandToJSON(requestParameters['deleteFileCommand']),
        };
    }

    /**
     */
    async apiFileDeleteRaw(requestParameters: ApiFileDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiFileDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiFileDelete(requestParameters: ApiFileDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiFileDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiFileDownloadGet without sending the request
     */
    async apiFileDownloadGetRequestOpts(requestParameters: ApiFileDownloadGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/File/download`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiFileDownloadGetRaw(requestParameters: ApiFileDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.apiFileDownloadGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async apiFileDownloadGet(requestParameters: ApiFileDownloadGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiFileDownloadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFileGet without sending the request
     */
    async apiFileGetRequestOpts(requestParameters: ApiFileGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        if (requestParameters['title'] != null) {
            queryParameters['Title'] = requestParameters['title'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/File`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiFileGetRaw(requestParameters: ApiFileGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FileDto>>> {
        const requestOptions = await this.apiFileGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FileDtoFromJSON));
    }

    /**
     */
    async apiFileGet(requestParameters: ApiFileGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FileDto>> {
        const response = await this.apiFileGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFilePatch without sending the request
     */
    async apiFilePatchRequestOpts(requestParameters: ApiFilePatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['uID'] != null) {
            formParams.append('UID', requestParameters['uID'] as any);
        }

        if (requestParameters['file'] != null) {
            formParams.append('File', requestParameters['file'] as any);
        }


        let urlPath = `/api/File`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async apiFilePatchRaw(requestParameters: ApiFilePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiFilePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiFilePatch(requestParameters: ApiFilePatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiFilePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFilePreviewGet without sending the request
     */
    async apiFilePreviewGetRequestOpts(requestParameters: ApiFilePreviewGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/File/preview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiFilePreviewGetRaw(requestParameters: ApiFilePreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.apiFilePreviewGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async apiFilePreviewGet(requestParameters: ApiFilePreviewGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiFilePreviewGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFileTagPatch without sending the request
     */
    async apiFileTagPatchRequestOpts(requestParameters: ApiFileTagPatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/File/tag`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFileTagCommandToJSON(requestParameters['updateFileTagCommand']),
        };
    }

    /**
     */
    async apiFileTagPatchRaw(requestParameters: ApiFileTagPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiFileTagPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiFileTagPatch(requestParameters: ApiFileTagPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiFileTagPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiFileUploadPost without sending the request
     */
    async apiFileUploadPostRequestOpts(requestParameters: ApiFileUploadPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            requestParameters['file'].forEach((element) => {
                formParams.append('File', element as any);
            })
        }


        let urlPath = `/api/File/Upload`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async apiFileUploadPostRaw(requestParameters: ApiFileUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiFileUploadPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiFileUploadPost(requestParameters: ApiFileUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiFileUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
