/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OverviewDto,
    OverviewDtoFromJSON,
    OverviewDtoToJSON,
} from '../models/OverviewDto';

export interface ApiOverviewGetRequest {
    recentCount?: number;
}

/**
 * OverviewApi - interface
 * 
 * @export
 * @interface OverviewApiInterface
 */
export interface OverviewApiInterface {
    /**
     * Creates request options for apiOverviewGet without sending the request
     * @param {number} [recentCount] 
     * @throws {RequiredError}
     * @memberof OverviewApiInterface
     */
    apiOverviewGetRequestOpts(requestParameters: ApiOverviewGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {number} [recentCount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OverviewApiInterface
     */
    apiOverviewGetRaw(requestParameters: ApiOverviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverviewDto>>;

    /**
     */
    apiOverviewGet(requestParameters: ApiOverviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverviewDto>;

}

/**
 * 
 */
export class OverviewApi extends runtime.BaseAPI implements OverviewApiInterface {

    /**
     * Creates request options for apiOverviewGet without sending the request
     */
    async apiOverviewGetRequestOpts(requestParameters: ApiOverviewGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['recentCount'] != null) {
            queryParameters['RecentCount'] = requestParameters['recentCount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Overview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiOverviewGetRaw(requestParameters: ApiOverviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverviewDto>> {
        const requestOptions = await this.apiOverviewGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverviewDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiOverviewGet(requestParameters: ApiOverviewGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverviewDto> {
        const response = await this.apiOverviewGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
