/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateTagCommand,
    CreateTagCommandFromJSON,
    CreateTagCommandToJSON,
} from '../models/CreateTagCommand';
import {
    type DeleteTagCommand,
    DeleteTagCommandFromJSON,
    DeleteTagCommandToJSON,
} from '../models/DeleteTagCommand';
import {
    type TagDto,
    TagDtoFromJSON,
    TagDtoToJSON,
} from '../models/TagDto';
import {
    type UpdateTagCommand,
    UpdateTagCommandFromJSON,
    UpdateTagCommandToJSON,
} from '../models/UpdateTagCommand';

export interface ApiTagDeleteRequest {
    deleteTagCommand?: DeleteTagCommand;
}

export interface ApiTagGetRequest {
    uID?: string;
    tag?: string;
}

export interface ApiTagPatchRequest {
    updateTagCommand?: UpdateTagCommand;
}

export interface ApiTagPostRequest {
    createTagCommand?: CreateTagCommand;
}

/**
 * TagApi - interface
 * 
 * @export
 * @interface TagApiInterface
 */
export interface TagApiInterface {
    /**
     * Creates request options for apiTagDelete without sending the request
     * @param {DeleteTagCommand} [deleteTagCommand] 
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagDeleteRequestOpts(requestParameters: ApiTagDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {DeleteTagCommand} [deleteTagCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagDeleteRaw(requestParameters: ApiTagDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiTagDelete(requestParameters: ApiTagDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for apiTagGet without sending the request
     * @param {string} [uID] 
     * @param {string} [tag] 
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagGetRequestOpts(requestParameters: ApiTagGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {string} [tag] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagGetRaw(requestParameters: ApiTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TagDto>>>;

    /**
     */
    apiTagGet(requestParameters: ApiTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TagDto>>;

    /**
     * Creates request options for apiTagPatch without sending the request
     * @param {UpdateTagCommand} [updateTagCommand] 
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagPatchRequestOpts(requestParameters: ApiTagPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {UpdateTagCommand} [updateTagCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagPatchRaw(requestParameters: ApiTagPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiTagPatch(requestParameters: ApiTagPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiTagPost without sending the request
     * @param {CreateTagCommand} [createTagCommand] 
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagPostRequestOpts(requestParameters: ApiTagPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateTagCommand} [createTagCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TagApiInterface
     */
    apiTagPostRaw(requestParameters: ApiTagPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiTagPost(requestParameters: ApiTagPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class TagApi extends runtime.BaseAPI implements TagApiInterface {

    /**
     * Creates request options for apiTagDelete without sending the request
     */
    async apiTagDeleteRequestOpts(requestParameters: ApiTagDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Tag`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteTagCommandToJSON(requestParameters['deleteTagCommand']),
        };
    }

    /**
     */
    async apiTagDeleteRaw(requestParameters: ApiTagDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTagDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTagDelete(requestParameters: ApiTagDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTagDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiTagGet without sending the request
     */
    async apiTagGetRequestOpts(requestParameters: ApiTagGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        if (requestParameters['tag'] != null) {
            queryParameters['Tag'] = requestParameters['tag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Tag`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiTagGetRaw(requestParameters: ApiTagGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TagDto>>> {
        const requestOptions = await this.apiTagGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TagDtoFromJSON));
    }

    /**
     */
    async apiTagGet(requestParameters: ApiTagGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TagDto>> {
        const response = await this.apiTagGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTagPatch without sending the request
     */
    async apiTagPatchRequestOpts(requestParameters: ApiTagPatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Tag`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTagCommandToJSON(requestParameters['updateTagCommand']),
        };
    }

    /**
     */
    async apiTagPatchRaw(requestParameters: ApiTagPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTagPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTagPatch(requestParameters: ApiTagPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTagPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTagPost without sending the request
     */
    async apiTagPostRequestOpts(requestParameters: ApiTagPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Tag`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTagCommandToJSON(requestParameters['createTagCommand']),
        };
    }

    /**
     */
    async apiTagPostRaw(requestParameters: ApiTagPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTagPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTagPost(requestParameters: ApiTagPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTagPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
