/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateTodoCommand,
    CreateTodoCommandFromJSON,
    CreateTodoCommandToJSON,
} from '../models/CreateTodoCommand';
import {
    type DeleteTodoCommand,
    DeleteTodoCommandFromJSON,
    DeleteTodoCommandToJSON,
} from '../models/DeleteTodoCommand';
import {
    type TodoDtoPageResult,
    TodoDtoPageResultFromJSON,
    TodoDtoPageResultToJSON,
} from '../models/TodoDtoPageResult';
import {
    type UpdateTodoCommand,
    UpdateTodoCommandFromJSON,
    UpdateTodoCommandToJSON,
} from '../models/UpdateTodoCommand';

export interface ApiTodoDeleteRequest {
    deleteTodoCommand?: DeleteTodoCommand;
}

export interface ApiTodoGetRequest {
    uID?: string;
    desc?: string;
    isTree?: boolean;
    page?: number;
    pageSize?: number;
}

export interface ApiTodoPatchRequest {
    updateTodoCommand?: UpdateTodoCommand;
}

export interface ApiTodoPostRequest {
    createTodoCommand?: CreateTodoCommand;
}

/**
 * TodoApi - interface
 * 
 * @export
 * @interface TodoApiInterface
 */
export interface TodoApiInterface {
    /**
     * Creates request options for apiTodoDelete without sending the request
     * @param {DeleteTodoCommand} [deleteTodoCommand] 
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoDeleteRequestOpts(requestParameters: ApiTodoDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {DeleteTodoCommand} [deleteTodoCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoDeleteRaw(requestParameters: ApiTodoDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiTodoDelete(requestParameters: ApiTodoDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for apiTodoGet without sending the request
     * @param {string} [uID] 
     * @param {string} [desc] 
     * @param {boolean} [isTree] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoGetRequestOpts(requestParameters: ApiTodoGetRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {string} [uID] 
     * @param {string} [desc] 
     * @param {boolean} [isTree] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoGetRaw(requestParameters: ApiTodoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDtoPageResult>>;

    /**
     */
    apiTodoGet(requestParameters: ApiTodoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDtoPageResult>;

    /**
     * Creates request options for apiTodoPatch without sending the request
     * @param {UpdateTodoCommand} [updateTodoCommand] 
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoPatchRequestOpts(requestParameters: ApiTodoPatchRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {UpdateTodoCommand} [updateTodoCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoPatchRaw(requestParameters: ApiTodoPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiTodoPatch(requestParameters: ApiTodoPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Creates request options for apiTodoPost without sending the request
     * @param {CreateTodoCommand} [createTodoCommand] 
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoPostRequestOpts(requestParameters: ApiTodoPostRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @param {CreateTodoCommand} [createTodoCommand] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TodoApiInterface
     */
    apiTodoPostRaw(requestParameters: ApiTodoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    apiTodoPost(requestParameters: ApiTodoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class TodoApi extends runtime.BaseAPI implements TodoApiInterface {

    /**
     * Creates request options for apiTodoDelete without sending the request
     */
    async apiTodoDeleteRequestOpts(requestParameters: ApiTodoDeleteRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteTodoCommandToJSON(requestParameters['deleteTodoCommand']),
        };
    }

    /**
     */
    async apiTodoDeleteRaw(requestParameters: ApiTodoDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiTodoDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTodoDelete(requestParameters: ApiTodoDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTodoDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiTodoGet without sending the request
     */
    async apiTodoGetRequestOpts(requestParameters: ApiTodoGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['uID'] != null) {
            queryParameters['UID'] = requestParameters['uID'];
        }

        if (requestParameters['desc'] != null) {
            queryParameters['Desc'] = requestParameters['desc'];
        }

        if (requestParameters['isTree'] != null) {
            queryParameters['IsTree'] = requestParameters['isTree'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiTodoGetRaw(requestParameters: ApiTodoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDtoPageResult>> {
        const requestOptions = await this.apiTodoGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDtoPageResultFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoGet(requestParameters: ApiTodoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDtoPageResult> {
        const response = await this.apiTodoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTodoPatch without sending the request
     */
    async apiTodoPatchRequestOpts(requestParameters: ApiTodoPatchRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTodoCommandToJSON(requestParameters['updateTodoCommand']),
        };
    }

    /**
     */
    async apiTodoPatchRaw(requestParameters: ApiTodoPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTodoPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTodoPatch(requestParameters: ApiTodoPatchRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTodoPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiTodoPost without sending the request
     */
    async apiTodoPostRequestOpts(requestParameters: ApiTodoPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Todo`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTodoCommandToJSON(requestParameters['createTodoCommand']),
        };
    }

    /**
     */
    async apiTodoPostRaw(requestParameters: ApiTodoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiTodoPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiTodoPost(requestParameters: ApiTodoPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiTodoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
