// <auto-generated />
using System;
using AqLife.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(AppStorage))]
    partial class AppStorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AqLife.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Avatar")
                        .HasColumnType("uuid");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoginPasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UID");

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.CorpusEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorpusContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UID");

                    b.HasIndex("CorpusContent")
                        .IsUnique();

                    b.ToTable("Corpus");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.File.FileMetaEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("FileSize")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("UID");

                    b.ToTable("FileMeta");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.File.InteractionMetaEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .HasColumnType("uuid");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("UID");

                    b.ToTable("FileInteractionMetas");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.File.PublishMetaEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublishStatus")
                        .HasColumnType("integer");

                    b.HasKey("UID");

                    b.ToTable("FilePublishMetas");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.FileTagEntity", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("FileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AID")
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SubscriptionIcon")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionPlatform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UID");

                    b.HasIndex("AID");

                    b.HasIndex("SubscriptionPlatform", "SubscriptionLink")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliasName")
                        .HasColumnType("text");

                    b.Property<bool>("IsCategory")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("UID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.TodoEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FTID")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UID");

                    b.HasIndex("FTID");

                    b.ToTable("TodoList");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.File.InteractionMetaEntity", b =>
                {
                    b.HasOne("AqLife.Domain.Entities.File.FileMetaEntity", null)
                        .WithOne("InteractionMeta")
                        .HasForeignKey("AqLife.Domain.Entities.File.InteractionMetaEntity", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AqLife.Domain.Entities.File.PublishMetaEntity", b =>
                {
                    b.HasOne("AqLife.Domain.Entities.File.FileMetaEntity", null)
                        .WithOne("PublishMeta")
                        .HasForeignKey("AqLife.Domain.Entities.File.PublishMetaEntity", "UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AqLife.Domain.Entities.FileTagEntity", b =>
                {
                    b.HasOne("AqLife.Domain.Entities.File.FileMetaEntity", "File")
                        .WithMany("FileTags")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AqLife.Domain.Entities.TagEntity", "Tag")
                        .WithMany("FileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("AqLife.Domain.Entities.AccountEntity", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("AID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AqLife.Domain.Entities.TodoEntity", b =>
                {
                    b.HasOne("AqLife.Domain.Entities.TodoEntity", null)
                        .WithMany("Children")
                        .HasForeignKey("FTID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AqLife.Domain.Entities.AccountEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.File.FileMetaEntity", b =>
                {
                    b.Navigation("FileTags");

                    b.Navigation("InteractionMeta")
                        .IsRequired();

                    b.Navigation("PublishMeta")
                        .IsRequired();
                });

            modelBuilder.Entity("AqLife.Domain.Entities.TagEntity", b =>
                {
                    b.Navigation("FileTags");
                });

            modelBuilder.Entity("AqLife.Domain.Entities.TodoEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
