/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTagCommand
 */
export interface DeleteTagCommand {
    /**
     * 
     * @type {string}
     * @memberof DeleteTagCommand
     */
    uid?: string;
}

/**
 * Check if a given object implements the DeleteTagCommand interface.
 */
export function instanceOfDeleteTagCommand(value: object): value is DeleteTagCommand {
    return true;
}

export function DeleteTagCommandFromJSON(json: any): DeleteTagCommand {
    return DeleteTagCommandFromJSONTyped(json, false);
}

export function DeleteTagCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTagCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
    };
}

export function DeleteTagCommandToJSON(json: any): DeleteTagCommand {
    return DeleteTagCommandToJSONTyped(json, false);
}

export function DeleteTagCommandToJSONTyped(value?: DeleteTagCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

