/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ISimpleAccountInfo
 */
export interface ISimpleAccountInfo {
    /**
     * 
     * @type {string}
     * @memberof ISimpleAccountInfo
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ISimpleAccountInfo
     */
    desc?: string | null;
}

/**
 * Check if a given object implements the ISimpleAccountInfo interface.
 */
export function instanceOfISimpleAccountInfo(value: object): value is ISimpleAccountInfo {
    return true;
}

export function ISimpleAccountInfoFromJSON(json: any): ISimpleAccountInfo {
    return ISimpleAccountInfoFromJSONTyped(json, false);
}

export function ISimpleAccountInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISimpleAccountInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'desc': json['desc'] == null ? undefined : json['desc'],
    };
}

export function ISimpleAccountInfoToJSON(json: any): ISimpleAccountInfo {
    return ISimpleAccountInfoToJSONTyped(json, false);
}

export function ISimpleAccountInfoToJSONTyped(value?: ISimpleAccountInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'desc': value['desc'],
    };
}

