/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCommand
 */
export interface LoginCommand {
    /**
     * 
     * @type {string}
     * @memberof LoginCommand
     */
    accountName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginCommand
     */
    secretKey?: string | null;
}

/**
 * Check if a given object implements the LoginCommand interface.
 */
export function instanceOfLoginCommand(value: object): value is LoginCommand {
    return true;
}

export function LoginCommandFromJSON(json: any): LoginCommand {
    return LoginCommandFromJSONTyped(json, false);
}

export function LoginCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'accountName': json['accountName'] == null ? undefined : json['accountName'],
        'secretKey': json['secretKey'] == null ? undefined : json['secretKey'],
    };
}

export function LoginCommandToJSON(json: any): LoginCommand {
    return LoginCommandToJSONTyped(json, false);
}

export function LoginCommandToJSONTyped(value?: LoginCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountName': value['accountName'],
        'secretKey': value['secretKey'],
    };
}

