/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionFullDto
 */
export interface SubscriptionFullDto {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionFullDto
     */
    aliasName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionFullDto
     */
    subscriptionLink?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionFullDto
     */
    subscriptionPlatform?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionFullDto
     */
    subscriptionIcon?: string | null;
    /**
     * 
     * @type {Blob}
     * @memberof SubscriptionFullDto
     */
    newIconFile?: Blob | null;
}

/**
 * Check if a given object implements the SubscriptionFullDto interface.
 */
export function instanceOfSubscriptionFullDto(value: object): value is SubscriptionFullDto {
    return true;
}

export function SubscriptionFullDtoFromJSON(json: any): SubscriptionFullDto {
    return SubscriptionFullDtoFromJSONTyped(json, false);
}

export function SubscriptionFullDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionFullDto {
    if (json == null) {
        return json;
    }
    return {
        
        'aliasName': json['aliasName'] == null ? undefined : json['aliasName'],
        'subscriptionLink': json['subscriptionLink'] == null ? undefined : json['subscriptionLink'],
        'subscriptionPlatform': json['subscriptionPlatform'] == null ? undefined : json['subscriptionPlatform'],
        'subscriptionIcon': json['subscriptionIcon'] == null ? undefined : json['subscriptionIcon'],
        'newIconFile': json['newIconFile'] == null ? undefined : json['newIconFile'],
    };
}

export function SubscriptionFullDtoToJSON(json: any): SubscriptionFullDto {
    return SubscriptionFullDtoToJSONTyped(json, false);
}

export function SubscriptionFullDtoToJSONTyped(value?: SubscriptionFullDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aliasName': value['aliasName'],
        'subscriptionLink': value['subscriptionLink'],
        'subscriptionPlatform': value['subscriptionPlatform'],
        'subscriptionIcon': value['subscriptionIcon'],
        'newIconFile': value['newIconFile'],
    };
}

