/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodoForAdd
 */
export interface TodoForAdd {
    /**
     * 
     * @type {string}
     * @memberof TodoForAdd
     */
    ftid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TodoForAdd
     */
    desc?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TodoForAdd
     */
    priority?: number;
}

/**
 * Check if a given object implements the TodoForAdd interface.
 */
export function instanceOfTodoForAdd(value: object): value is TodoForAdd {
    return true;
}

export function TodoForAddFromJSON(json: any): TodoForAdd {
    return TodoForAddFromJSONTyped(json, false);
}

export function TodoForAddFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoForAdd {
    if (json == null) {
        return json;
    }
    return {
        
        'ftid': json['ftid'] == null ? undefined : json['ftid'],
        'desc': json['desc'] == null ? undefined : json['desc'],
        'priority': json['priority'] == null ? undefined : json['priority'],
    };
}

export function TodoForAddToJSON(json: any): TodoForAdd {
    return TodoForAddToJSONTyped(json, false);
}

export function TodoForAddToJSONTyped(value?: TodoForAdd | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ftid': value['ftid'],
        'desc': value['desc'],
        'priority': value['priority'],
    };
}

