/* tslint:disable */
/* eslint-disable */
/**
 * Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFileCommand
 */
export interface UpdateFileCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateFileCommand
     */
    uid?: string;
    /**
     * 
     * @type {Blob}
     * @memberof UpdateFileCommand
     */
    file?: Blob | null;
}

/**
 * Check if a given object implements the UpdateFileCommand interface.
 */
export function instanceOfUpdateFileCommand(value: object): value is UpdateFileCommand {
    return true;
}

export function UpdateFileCommandFromJSON(json: any): UpdateFileCommand {
    return UpdateFileCommandFromJSONTyped(json, false);
}

export function UpdateFileCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFileCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'] == null ? undefined : json['uid'],
        'file': json['file'] == null ? undefined : json['file'],
    };
}

export function UpdateFileCommandToJSON(json: any): UpdateFileCommand {
    return UpdateFileCommandToJSONTyped(json, false);
}

export function UpdateFileCommandToJSONTyped(value?: UpdateFileCommand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'file': value['file'],
    };
}

