// <auto-generated />
using System;
using AqLife.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


#nullable disable

namespace AqLife.Data.Migrations
{
    [DbContext(typeof(AppStorage))]
    [Migration("20260508033306_OptimizeDataStructures")]
    partial class OptimizeDataStructures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AqLife.Data.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("UID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AqLife.Data.Entities.CorpusEntity", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CorpusContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Gid");

                    b.ToTable("Corpus");
                });

            modelBuilder.Entity("AqLife.Data.Entities.DemoEntity", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Serial"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Serial");

                    b.ToTable("Demo");
                });

            modelBuilder.Entity("AqLife.Data.Entities.FileIndexEntity", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DesensitizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Uuid");

                    b.ToTable("File");
                });

            modelBuilder.Entity("AqLife.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("SID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SubscriptionIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubscriptionLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubscriptionPlatform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UID")
                        .HasColumnType("char(36)");

                    b.HasKey("SID");

                    b.HasIndex("UID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AqLife.Data.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("AqLife.Data.Entities.AccountEntity", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AqLife.Data.Entities.AccountEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
