// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLife.Infrastructure;

#nullable disable

namespace MyLife.Data.Migrations
{
    [DbContext(typeof(AppStorage))]
    [Migration("20260730140429_corpusModelOptimize")]
    partial class corpusModelOptimize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyLife.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Avatar")
                        .HasColumnType("char(36)");

                    b.Property<string>("Desc")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginPasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("UID");

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.CorpusEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CorpusContent")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UID");

                    b.HasIndex("CorpusContent")
                        .IsUnique();

                    b.ToTable("Corpus");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.FileMetaEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UID");

                    b.ToTable("FileMeta");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.FileTagEntity", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("FileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AID")
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid?>("SubscriptionIcon")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubscriptionLink")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubscriptionPlatform")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UID");

                    b.HasIndex("AID");

                    b.HasIndex("SubscriptionPlatform", "SubscriptionLink")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCategory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("UID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.TodoEntity", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("FTID")
                        .HasColumnType("char(36)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.HasIndex("FTID");

                    b.ToTable("TodoList");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.FileTagEntity", b =>
                {
                    b.HasOne("MyLife.Domain.Entities.FileMetaEntity", "File")
                        .WithMany("FileTags")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyLife.Domain.Entities.TagEntity", "Tag")
                        .WithMany("FileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("MyLife.Domain.Entities.AccountEntity", "Account")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.TodoEntity", b =>
                {
                    b.HasOne("MyLife.Domain.Entities.TodoEntity", null)
                        .WithMany("Children")
                        .HasForeignKey("FTID");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.AccountEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.FileMetaEntity", b =>
                {
                    b.Navigation("FileTags");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.TagEntity", b =>
                {
                    b.Navigation("FileTags");
                });

            modelBuilder.Entity("MyLife.Domain.Entities.TodoEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
